version: '3'
services:
  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark-master
    container_name: spark-master
    ports:
      - "9999:9999"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_PUBLIC_DNS=localhost

  spark-worker-1:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://localhost:7077"
      - SPARK_PUBLIC_DNS=localhost
    network_mode: host

  # spark-worker-2:
  #   build:
  #     context: ./spark
  #     dockerfile: Dockerfile.spark-worker
  #   container_name: spark-worker-2
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8082:8081"
  #   environment:
  #     - "SPARK_MASTER=spark://host.docker.internal:7077"
  #     - SPARK_PUBLIC_DNS=localhost

  streamprocessor:
    build: .
    container_name: StreamProcessor
    ports:
      - "8002:8002"
      - "4040:4040"
    environment:
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - spark-master
      - spark-worker-1
      # - spark-worker-2
    network_mode: host
    extra_hosts:
      spark-master: 127.0.0.1
