version: '3'
services:
  cassandra:
    image: cassandra:3.11.3
    container_name: cassandra
    ports:
      - '9042:9042'
    environment:
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
      CASSANDRA_USER: cassandra
      CASSANDRA_HOST: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      CASSANDRA_NUM_TOKENS: 128
      CASSANDRA_DATACENTER: DataCenter1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 15s
      timeout: 10s
      retries: 8
